# Generated by Django 3.0.8 on 2020-07-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200705_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.FloatField(max_length=30, null=True),
        ),
    ]
